name: dailytaskmanager
description: "A task management app that combines personal and collaborative modes."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  # Firebase packages
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  # State management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  # UI packages
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  # Utilities
  intl: ^0.19.0
  uuid: ^4.2.2
  path_provider: ^2.1.1
  file_picker: ^6.1.1
  # Charts for analytics
  fl_chart: ^0.65.0
  # Drag and drop functionality
  reorderables: ^0.6.0
  # CSV export
  csv: ^5.1.1
  # Authentication
  google_sign_in: ^6.1.6
  github_sign_in: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
